# ========== 核心适配：你的跑道检测专用配置 ==========
dataset= 'Tusimple'
data_root= 'UFLD_dataset'  # 必须修改：你的数据集根目录（如D:/runway_dataset）
epoch= 150                      # 源码默认100轮，对2车道足够，不用改
batch_size= 64                  # 根据GPU显存调整：8G显存改8/16，16G改32，32G保留32
optimizer= 'SGD'                # 源码默认SGD，不用改
learning_rate= 0.05             # SGD默认学习率，适配Res18
weight_decay= 0.0001            # 源码默认，不用改
momentum= 0.9                   # SGD动量，不用改
scheduler= 'multi'              # 多步学习率衰减，不用改
steps= [50,75]                  # 50/75轮学习率降为1/10，不用改
gamma= 0.1                      # 衰减系数，不用改
warmup= 'linear'                # 线性热身，不用改
warmup_iters= 100               # 热身迭代数，不用改
backbone= '18'                  # Res18，源码默认，不用改
griding_num= 100                # 列锚点数量，UFLDv2核心，不用改
use_aux= False                  # 先关闭辅助分割，训练核心任务
sim_loss_w= 0.0                 # 2车道无需相似性损失，保留0
shp_loss_w= 0.0                 # 2车道无需形状损失，保留0
note= 'runway_res18_2lanes'     # 训练备注，方便识别
log_path= 'logs/runway_train'   # 日志保存路径，自动创建
finetune= '../UFLDv2/model/tusimple_res18.pth'                  # 从零训练，不用预训练权重
resume= None                    # 不恢复训练
test_model= r'D:\program\HoriLane\RunwayDetection\UFLDv2\model\model_best.pth'                  # 训练完再填，用于测试
test_work_dir= 'test_results'   # 测试结果保存路径
num_lanes= 2                    # 核心修改：从4改成2（你的跑道线数量）
var_loss_power= 2.0             # 损失幂次，不用改
auto_backup= True               # 自动备份模型，不用改
num_row= 56                     # 行锚点数量，和你的转换脚本一致
num_col= 56                     # 列数，源码默认，不用改
train_width= 800                # 训练时图像宽度（源码默认，会自动Resize）
train_height= 320               # 训练时图像高度（源码默认，适配Res18）
num_cell_row= 150               # 行单元格数，不用改
num_cell_col= 120               # 列单元格数，不用改
mean_loss_w= 0.05               # 均值损失权重，不用改
fc_norm= False                  # 全连接层归一化，不用改
soft_loss= True                 # 软损失，提升精度，不用改
cls_loss_col_w= 1.0             # 列分类损失权重，不用改
cls_ext_col_w= 1.0              # 扩展列损失权重，不用改
mean_loss_col_w= 0.05           # 列均值损失权重，不用改
eval_mode= 'normal'             # 评估模式，不用改
crop_ratio = 1               # 裁剪比例，不用改
cache_path = 'UFLD_dataset/tusimple_anon_cache.json'
row_anchor = 0
col_anchor = 0
origin_width = 1920
origin_height = 1080
num_lanes = 2
use_ema = True