# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\program\HoriLane\RunwayDetection\Qt\ui\dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 300)
        self.videoPushButton = QtWidgets.QPushButton(Dialog)
        self.videoPushButton.setGeometry(QtCore.QRect(120, 90, 131, 51))
        self.videoPushButton.setObjectName("videoPushButton")
        self.imagePushButton = QtWidgets.QPushButton(Dialog)
        self.imagePushButton.setGeometry(QtCore.QRect(120, 180, 131, 51))
        self.imagePushButton.setObjectName("imagePushButton")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.videoPushButton.setText(_translate("Dialog", "Video Mode"))
        self.imagePushButton.setText(_translate("Dialog", "Image Mode"))
