# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\program\HoriLane\RunwayDetection\Qt\ui\imagewidget.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ImageWidget(object):
    def setupUi(self, ImageWidget):
        ImageWidget.setObjectName("ImageWidget")
        ImageWidget.resize(1490, 659)
        self.selectButton = QtWidgets.QPushButton(ImageWidget)
        self.selectButton.setGeometry(QtCore.QRect(270, 540, 171, 71))
        self.selectButton.setObjectName("selectButton")
        self.solveButton = QtWidgets.QPushButton(ImageWidget)
        self.solveButton.setGeometry(QtCore.QRect(660, 540, 171, 71))
        self.solveButton.setObjectName("solveButton")
        self.reSelectButton = QtWidgets.QPushButton(ImageWidget)
        self.reSelectButton.setGeometry(QtCore.QRect(1040, 540, 171, 71))
        self.reSelectButton.setObjectName("reSelectButton")
        self.label = QtWidgets.QLabel(ImageWidget)
        self.label.setGeometry(QtCore.QRect(10, 50, 721, 431))
        self.label.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(ImageWidget)
        self.label_2.setGeometry(QtCore.QRect(760, 50, 721, 431))
        self.label_2.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.label_2.setObjectName("label_2")

        self.retranslateUi(ImageWidget)
        QtCore.QMetaObject.connectSlotsByName(ImageWidget)

    def retranslateUi(self, ImageWidget):
        _translate = QtCore.QCoreApplication.translate
        ImageWidget.setWindowTitle(_translate("ImageWidget", "Form"))
        self.selectButton.setText(_translate("ImageWidget", "选择照片文件"))
        self.solveButton.setText(_translate("ImageWidget", "进行姿态解算"))
        self.reSelectButton.setText(_translate("ImageWidget", "重新选择模式"))
        self.label.setText(_translate("ImageWidget", "TextLabel"))
        self.label_2.setText(_translate("ImageWidget", "TextLabel"))
