# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\program\HoriLane\RunwayDetection\Qt\ui\pnp_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_PNP_Window(object):
    def setupUi(self, PNP_Window):
        PNP_Window.setObjectName("PNP_Window")
        PNP_Window.resize(659, 886)
        self.axes_label = QtWidgets.QLabel(PNP_Window)
        self.axes_label.setGeometry(QtCore.QRect(30, 170, 91, 41))
        self.axes_label.setObjectName("axes_label")
        self.plot_abel_2 = QtWidgets.QLabel(PNP_Window)
        self.plot_abel_2.setGeometry(QtCore.QRect(20, 630, 71, 41))
        self.plot_abel_2.setObjectName("plot_abel_2")
        self.axes_widget = QtWidgets.QWidget(PNP_Window)
        self.axes_widget.setGeometry(QtCore.QRect(130, 10, 491, 371))
        self.axes_widget.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.axes_widget.setObjectName("axes_widget")
        self.plot_widget_2 = QtWidgets.QWidget(PNP_Window)
        self.plot_widget_2.setGeometry(QtCore.QRect(110, 480, 491, 381))
        self.plot_widget_2.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.plot_widget_2.setObjectName("plot_widget_2")
        self.pushButton = QtWidgets.QPushButton(PNP_Window)
        self.pushButton.setGeometry(QtCore.QRect(10, 410, 91, 41))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(PNP_Window)
        self.pushButton_2.setGeometry(QtCore.QRect(150, 410, 101, 41))
        self.pushButton_2.setObjectName("pushButton_2")

        self.retranslateUi(PNP_Window)
        QtCore.QMetaObject.connectSlotsByName(PNP_Window)

    def retranslateUi(self, PNP_Window):
        _translate = QtCore.QCoreApplication.translate
        PNP_Window.setWindowTitle(_translate("PNP_Window", "Form"))
        self.axes_label.setText(_translate("PNP_Window", "坐标轴显示："))
        self.plot_abel_2.setText(_translate("PNP_Window", "轨迹解算："))
        self.pushButton.setText(_translate("PNP_Window", "开始"))
        self.pushButton_2.setText(_translate("PNP_Window", "重播"))
