# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\program\HoriLane\RunwayDetection\Qt\ui\widget.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Widget(object):
    def setupUi(self, Widget):
        Widget.setObjectName("Widget")
        Widget.resize(992, 669)
        self.widget = QtWidgets.QWidget(Widget)
        self.widget.setGeometry(QtCore.QRect(20, 10, 951, 441))
        self.widget.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.widget.setObjectName("widget")
        self.selectpushButton = QtWidgets.QPushButton(Widget)
        self.selectpushButton.setGeometry(QtCore.QRect(20, 560, 131, 51))
        self.selectpushButton.setObjectName("selectpushButton")
        self.playpushButton_2 = QtWidgets.QPushButton(Widget)
        self.playpushButton_2.setGeometry(QtCore.QRect(180, 560, 131, 51))
        self.playpushButton_2.setObjectName("playpushButton_2")
        self.pausepushButton_3 = QtWidgets.QPushButton(Widget)
        self.pausepushButton_3.setGeometry(QtCore.QRect(340, 560, 131, 51))
        self.pausepushButton_3.setObjectName("pausepushButton_3")
        self.timehorizontalSlider = QtWidgets.QSlider(Widget)
        self.timehorizontalSlider.setGeometry(QtCore.QRect(40, 460, 831, 31))
        self.timehorizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.timehorizontalSlider.setObjectName("timehorizontalSlider")
        self.volumehorizontalSlider_2 = QtWidgets.QSlider(Widget)
        self.volumehorizontalSlider_2.setGeometry(QtCore.QRect(500, 510, 301, 20))
        self.volumehorizontalSlider_2.setOrientation(QtCore.Qt.Horizontal)
        self.volumehorizontalSlider_2.setObjectName("volumehorizontalSlider_2")
        self.volumelabel = QtWidgets.QLabel(Widget)
        self.volumelabel.setGeometry(QtCore.QRect(370, 510, 101, 21))
        self.volumelabel.setObjectName("volumelabel")
        self.actimelabel_2 = QtWidgets.QLabel(Widget)
        self.actimelabel_2.setGeometry(QtCore.QRect(70, 500, 161, 31))
        self.actimelabel_2.setObjectName("actimelabel_2")
        self.PNPpushButton_4 = QtWidgets.QPushButton(Widget)
        self.PNPpushButton_4.setGeometry(QtCore.QRect(790, 560, 131, 51))
        self.PNPpushButton_4.setObjectName("PNPpushButton_4")
        self.reSelectButton = QtWidgets.QPushButton(Widget)
        self.reSelectButton.setGeometry(QtCore.QRect(500, 560, 131, 51))
        self.reSelectButton.setObjectName("reSelectButton")

        self.retranslateUi(Widget)
        QtCore.QMetaObject.connectSlotsByName(Widget)

    def retranslateUi(self, Widget):
        _translate = QtCore.QCoreApplication.translate
        Widget.setWindowTitle(_translate("Widget", "Widget"))
        self.selectpushButton.setText(_translate("Widget", "选择文件"))
        self.playpushButton_2.setText(_translate("Widget", "播放"))
        self.pausepushButton_3.setText(_translate("Widget", "暂停"))
        self.volumelabel.setText(_translate("Widget", "<html><head/><body><p align=\"center\">音量</p></body></html>"))
        self.actimelabel_2.setText(_translate("Widget", "00:00/00:00"))
        self.PNPpushButton_4.setText(_translate("Widget", "PNP解算"))
        self.reSelectButton.setText(_translate("Widget", "重新选择模式"))
